_wandb:
    value:
        cli_version: 0.19.8
        m: []
        python_version: 3.10.12
        t:
            "1":
                - 1
                - 11
                - 41
                - 49
                - 51
                - 55
                - 71
                - 83
                - 98
                - 105
            "2":
                - 1
                - 11
                - 41
                - 49
                - 51
                - 55
                - 71
                - 83
                - 98
                - 105
            "3":
                - 13
                - 16
                - 23
                - 55
                - 61
            "4": 3.10.12
            "5": 0.19.8
            "6": 4.50.2
            "8":
                - 5
            "12": 0.19.8
            "13": linux-x86_64
dataset_name:
    value: celeba_hq_128_2700train
eval_batch_size:
    value: 16
gradient_accumulation_steps:
    value: 1
image_size:
    value: 128
learning_rate:
    value: 2e-05
lr_warmup_steps:
    value: 500
mixed_precision:
    value: fp16
model:
    value: unet_notebook
num_epochs:
    value: 300
num_train_timesteps:
    value: 750
output_dir:
    value: checkpoints/unet_notebook_0.00002_v3_20250327_121316
overwrite_output_dir:
    value: false
run_name:
    value: unet_notebook_0.00002_v3_20250327_121316
save_image_epochs:
    value: 5
save_model_epochs:
    value: 5
seed:
    value: 42
train_batch_size:
    value: 16
train_dir:
    value: data/celeba_hq_split/train
use_wandb:
    value: true
val_dir:
    value: data/celeba_hq_split/test
val_n_samples:
    value: 100
wandb_entity:
    value: tin-hoang
wandb_project:
    value: EEEM068_Diffusion_Models
weight_decay:
    value: 0.01
